<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProdukSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('produks')->insert([
            // --- KATEGORI RPL (0) ---
            [
                'nama_produk' => 'Website',
                'deskripsi' => 'Jasa pembuatan website.',
                'harga' => '500000',
                'foto' => 'produk_rpl2.png',
                'kategori_id' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Jasa Pembuatan Aplikasi',
                'deskripsi' => 'Jasa pembuatan aplikasi.',
                'harga' => '1000000',
                'foto' => 'produk_rpl3.png',
                'kategori_id' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Jasa Web Service',
                'deskripsi' => 'Jasa web service.',
                'harga' => '500000',
                'foto' => 'produk_rpl1.png',
                'kategori_id' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // --- KATEGORI ANIMASI (1) ---
            [
                'nama_produk' => 'Jasa Pembuatan Animasi',
                'deskripsi' => 'Jasa pembuatan animasi.',
                'harga' => '500000',
                'foto' => 'produk_animasi.png',
                'kategori_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // --- KATEGORI TKJ (2) ---
            [
                'nama_produk' => 'Instalasi Jaringan Nirkabel',
                'deskripsi' => 'Layanan pemasangan dan konfigurasi jaringan nirkabel (wireless) yang andal dan aman.',
                'harga' => '200000',
                'foto' => 'produk_tkj_nirkabel.jpeg',
                'kategori_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Koneksi Internet Tercepat dan Stabil',
                'deskripsi' => 'Optimasi dan setup jaringan untuk memastikan koneksi internet yang stabil dan berkecepatan tinggi.',
                'harga' => '150000',
                'foto' => 'produk_tkj_internet.jpeg',
                'kategori_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Jasa Instalasi Nirkabel',
                'deskripsi' => 'Jasa setting perangkat akses poin, router, dan perangkat pendukung jaringan nirkabel area luas.',
                'harga' => '200000',
                'foto' => 'produk_tkj_setting.jpeg',
                'kategori_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Jasa Service Software Profesional',
                'deskripsi' => 'Perbaikan, instalasi ulang sistem operasi, dan pembersihan software komputer atau laptop.',
                'harga' => '100000',
                'foto' => 'produk_tkj_service.jpeg',
                'kategori_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // --- KATEGORI PSPT (3) ---
           [
                'nama_produk' => 'News Magazine',
                'deskripsi' => 'Menerima publikasi media online dan visual, berita untuk semua dalam satu layanan.',
                'harga' => '250000',
                'foto' => 'produk_news_magazine.png',
                'kategori_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Feature Media',
                'deskripsi' => 'Menerima publikasi media feature sejarah, wisata, kuliner, dan lainnya secara informatif dan inspiratif.',
                'harga' => '250000',
                'foto' => 'produk_feature.png',
                'kategori_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Jasa Dokumenter',
                'deskripsi' => 'Menerima publikasi media dokumenter perusahaan, instansi, atau organisasi dengan kualitas tinggi.',
                'harga' => '500000',
                'foto' => 'dkv_2.jpeg',
                'kategori_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Acara Talk Show',
                'deskripsi' => 'Menerima acara talk show live dan siaran tunda dengan studio & multicam profesional.',
                'harga' => '750000',
                'foto' => 'dkv_1.jpeg',
                'kategori_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Pelatihan / Workshop Jurnalistik',
                'deskripsi' => 'Pemberdayaan melalui informasi dan keterampilan bercerita, literasi digital, dan jurnalisme warga.',
                'harga' => '350000',
                'foto' => 'produk_jurnalistik.jpeg',
                'kategori_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Pembuatan Film Drama',
                'deskripsi' => 'Layanan produksi profesional untuk narasi dramatik yang bermakna, fokus pada emosi dan karakter.',
                'harga' => '1500000',
                'foto' => 'produk_film_drama.jpeg',
                'kategori_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Film Sinematik Berbasis AI',
                'deskripsi' => 'Professional AI-Based Cinematic Film Production Services dengan AI storytelling dan cinematic rendering.',
                'harga' => '1000000',
                'foto' => 'produk_ai_cinematic.jpeg',
                'kategori_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Iklan Layanan Masyarakat',
                'deskripsi' => 'Pembuatan iklan layanan masyarakat untuk edukasi publik, penyuluhan kesehatan, dan keselamatan warga.',
                'harga' => '400000',
                'foto' => 'produk_iklan_layanan.jpeg',
                'kategori_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Jasa Podcast & Live Streaming',
                'deskripsi' => 'Menerima acara podcast live dan siaran tunda (on-demand) dengan audio dan video berkualitas tinggi.',
                'harga' => '300000',
                'foto' => 'produk_podcast.jpeg',
                'kategori_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // --- KATEGORI DKV (4) ---
            [
                'nama_produk' => 'Paperbag',
                'deskripsi' => 'Pembuatan paperbag custom yang kuat dan ramah lingkungan.',
                'harga' => '10000',
                'foto' => 'produk_dkv2.png',
                'kategori_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Jasa Design',
                'deskripsi' => 'Jasa desain untuk poster, media promosi, dan kebutuhan visual lainnya.',
                'harga' => '50000',
                'foto' => 'produk_dkv3.png',
                'kategori_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Name Tag',
                'deskripsi' => 'Pembuatan name tag untuk kegiatan sekolah, acara, dan organisasi.',
                'harga' => '15000',
                'foto' => 'produk_dkv1.png',
                'kategori_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Gantungan Kunci',
                'deskripsi' => 'Pembuatan gantungan kunci custom dengan cetakan berkualitas tinggi.',
                'harga' => '10000',
                'foto' => 'produk_dkv4.png',
                'kategori_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Desain Kaos',
                'deskripsi' => 'Jasa desain ilustrasi/vektor custom untuk kaos atau pakaian.',
                'harga' => '75000',
                'foto' => 'kaos desain.jpeg',
                'kategori_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Desain Banner',
                'deskripsi' => 'Layanan cetak banner promosi luar ruangan yang tahan air dan tajam.',
                'harga' => '40000',
                'foto' => 'banner.jpeg',
                'kategori_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Desain Logo',
                'deskripsi' => 'Pembuatan identitas visual atau logo profesional untuk branding usaha.',
                'harga' => '150000',
                'foto' => 'logo.jpeg',
                'kategori_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Desain Kemasan',
                'deskripsi' => 'Desain kemasan/packaging produk yang menarik dan estetis.',
                'harga' => '50000',
                'foto' => 'kemasan.jpeg',
                'kategori_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Undangan',
                'deskripsi' => 'Jasa desain dan cetak berbagai jenis surat undangan.',
                'harga' => '5000',
                'foto' => 'undangan.jpeg',
                'kategori_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Poster',
                'deskripsi' => 'Desain dan cetak poster informatif atau promosi.',
                'harga' => '15000',
                'foto' => 'poster_tefa.jpeg',
                'kategori_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Spanduk',
                'deskripsi' => 'Layanan cetak spanduk outdoor yang awet dan tahan air.',
                'harga' => '35000',
                'foto' => 'spanduk.jpeg',
                'kategori_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Baliho',
                'deskripsi' => 'Pembuatan desain dan cetak baliho berukuran besar.',
                'harga' => '50000',
                'foto' => 'baliho.jpeg',
                'kategori_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // --- KATEGORI GIM (5) ---
            [
                'nama_produk' => 'Pembuatan Gim',
                'deskripsi' => 'Jasa pembuatan gim.',
                'harga' => '750000',
                'foto' => 'produk_gim1.png',
                'kategori_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Aset 3D',
                'deskripsi' => 'Pembuatan aset 3D untuk kebutuhan desain, animasi, dan gim.',
                'harga' => '150000',
                'foto' => 'produk_gim2.png',
                'kategori_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}