<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProdukSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('produks')->insert([
            [
                'nama_produk' => 'Website',
                'deskripsi' => 'Jasa pembuatan website.',
                'harga' => '500000',
                'foto' => 'produk_rpl2.png',
                'kategori_id' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Pembuatan Gim',
                'deskripsi' => 'Jasa pembuatan gim.',
                'harga' => '750000',
                'foto' => 'produk_gim1.png',
                'kategori_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Aset 3D',
                'deskripsi' => 'Pembuatan aset 3D untuk kebutuhan desain, animasi, dan gim.',
                'harga' => '150000',
                'foto' => 'produk_gim2.png',
                'kategori_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Paperbag',
                'deskripsi' => 'Pembuatan paperbag custom yang kuat dan ramah lingkungan.',
                'harga' => '5.000 - 25.000',
                'foto' => 'produk_dkv2.png',
                'kategori_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Jasa Design',
                'deskripsi' => 'Jasa desain untuk poster, media promosi, dan kebutuhan visual lainnya.',
                'harga' => '30.000 - 150.000',
                'foto' => 'produk_dkv3.png',
                'kategori_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Name Tag',
                'deskripsi' => 'Pembuatan name tag untuk kegiatan sekolah, acara, dan organisasi.',
                'harga' => '10.000 - 35.000',
                'foto' => 'produk_dkv1.png',
                'kategori_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Gantungan Kunci',
                'deskripsi' => 'Pembuatan gantungan kunci custom dengan cetakan berkualitas tinggi.',
                'harga' => '5.000 - 20.000',
                'foto' => 'produk_dkv4.png',
                'kategori_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Desain Kaos',
                'deskripsi' => 'Jasa desain ilustrasi/vektor custom untuk kaos atau pakaian dengan format file siap cetak.',
                'harga' => '35.000 - 150.000',
                'foto' => 'kaos desain.jpeg',
                'kategori_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Desain Banner',
                'deskripsi' => 'Layanan cetak banner promosi luar ruangan yang tahan air dan tajam.',
                'harga' => '20.000 - 75.000',
                'foto' => 'banner.jpeg',
                'kategori_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Desain Logo',
                'deskripsi' => 'Pembuatan identitas visual atau logo profesional untuk branding usaha atau bisnis.',
                'harga' => '50.000 - 500.000',
                'foto' => 'logo.jpeg',
                'kategori_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Desain Kemasan',
                'deskripsi' => 'Desain kemasan/packaging produk yang menarik dan estetis untuk meningkatkan nilai jual.',
                'harga' => '15.000 - 150.000',
                'foto' => 'kemasan.jpeg',
                'kategori_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Undangan',
                'deskripsi' => 'Jasa desain dan cetak berbagai jenis surat undangan dengan pilihan gaya eksklusif.',
                'harga' => '2.000 - 15.000',
                'foto' => 'undangan.jpeg',
                'kategori_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Poster',
                'deskripsi' => 'Desain dan cetak poster informatif atau promosi dengan warna tajam dan kualitas tinggi.',
                'harga' => '5.000 - 35.000',
                'foto' => 'poster_tefa.jpeg',
                'kategori_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Spanduk',
                'deskripsi' => 'Layanan cetak spanduk outdoor yang awet, tahan air, dan jelas untuk media promosi.',
                'harga' => '20.000 - 60.000',
                'foto' => 'spanduk.jpeg',
                'kategori_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Baliho',
                'deskripsi' => 'Pembuatan desain dan cetak baliho berukuran besar untuk media informasi atau iklan komersial.',
                'harga' => '30.000 - 90.000',
                'foto' => 'baliho.jpeg',
                'kategori_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Sewa Studio Podcast',
                'deskripsi' => 'Jasa penyewaan studio podcast untuk kebutuhan rekaman.',
                'harga' => '100000',
                'foto' => 'produk_pspt.png',
                'kategori_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Jasa Pemasangan WiFi',
                'deskripsi' => 'Jasa pemasangan jaringan WiFi untuk kebutuhan rumah, sekolah, dan usaha.',
                'harga' => '150000',
                'foto' => 'produk_tkj.png',
                'kategori_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Jasa Pembuatan Aplikasi',
                'deskripsi' => 'Jasa pembuatan aplikasi.',
                'harga' => '1.000.000',
                'foto' => 'produk_rpl3.png',
                'kategori_id' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Jasa Web Service',
                'deskripsi' => 'Jasa web service.',
                'harga' => '500000',
                'foto' => 'produk_rpl1.png',
                'kategori_id' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Jasa Edit',
                'deskripsi' => 'Jasa editing foto atau video.',
                'harga' => '100000',
                'foto' => 'jasa_edit.png',
                'kategori_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Jasa Pembuatan Animasi',
                'deskripsi' => 'Jasa pembuatan animasi.',
                'harga' => '500000',
                'foto' => 'produk_animasi.png',
                'kategori_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}